services: 
  web:
    container_name: shortener
    build: 
      context: ./
      dockerfile: Dockerfile-local
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8004:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: shortener_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - shortener_data:/var/lib/postgresql/data
    env_file: ./.env

  redis:
    image: redis
    container_name: shortener_redis
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: shortener_celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  shortener_data:
